### ISSUE TITLE
How to launch controllers from the first time?

### ISSUE THREAD

**Issue by Katrin0522** [TrueOpenVR/TrueOpenVR-DIY#10]
Такая проблема, каждый раз когда включаю SteamVR, у меня почти всегда один из контроллеров не поворачивается, либо же нажимаются хаотично все кнопки что есть. А может и вообще не запуститься. Только с 15-20ой попытки возможно запустить нормально со всеми поворотами.. Как можно облегчить ситуацию/исправить? Использую два 3-ех метровых провода, на коротком проводе те же самые признаки. 10 Windows 1809.

**Comment by r57zone** [comment]
Можно попробовать с этим драйвером, распаковав в папку drivers trueopenvr settings, с заменой. Если нажать на F11 поможет или нет с убираем задержки? 
[ArduinoControllersNew.zip](https://github.com/TrueOpenVR/TrueOpenVR-DIY/files/8472766/ArduinoControllersNew.zip)

**Comment by Katrin0522** [comment]
Нажимать F11 будучи уже запущенным в SteamVR? или перед надо?

**Comment by r57zone** [comment]
После запуска да, когда появится задержка

**Comment by Katrin0522** [comment]
Проверила, работает. И ещё вопросик, как быть если вдруг провод вылетел из контроллера( было такое раз), и когда вставляешь обратно, как можно вернуть работоспособность без перезагрузки SteamVR? Или же невозможно?

**Comment by r57zone** [comment]
Пока невозможно, если есть возможность запишите видео с работой контроллеров, было бы очень интересно посмотреть. Сам стим вр там или в игре какой.

**Comment by Katrin0522** [comment]
> Пока невозможно, если есть возможность запишите видео с работой контроллеров, было бы очень интересно посмотреть. Сам стим вр там или в игре какой.

Да, конечно, если не забуду, скину вам на почту.

**Comment by r57zone** [comment]
Сделал еще очиску очереди на центрирование, нужно нажать на контроллера - "Grip" + "System", на обоих контроллерах.
[ArduinoControllersNew2.zip](https://github.com/TrueOpenVR/TrueOpenVR-DIY/files/8474928/ArduinoControllersNew2.zip)
Если есть возможность еще проверить, было бы здорово и я обновлю для всех это версию.

**Comment by Katrin0522** [comment]
> Сделал еще очиску очереди на центрирование, нужно нажать на контроллера - "Grip" + "System", на обоих контроллерах.
> [ArduinoControllersNew2.zip](https://github.com/TrueOpenVR/TrueOpenVR-DIY/files/8474928/ArduinoControllersNew2.zip)
> Если есть возможность еще проверить, было бы здорово и я обновлю для всех это версию.
> 

Завтра на правый контрлллер сделаю кнопку System(а то я забыла про центрование).
Завтра как доделаю дело с контроллером - проверю и скажу что да как. Фичу с F11 ещё тестю, вроде работает..

**Comment by Katrin0522** [comment]
Так.. поставила то что вы скинули, при сбросе правый контроллер сбрасывает в не те значения, изза чего косит налево по y на градусов ~ 45, изза чего приходится перезапускать стимвр чтобы все было ок, сейчас протесты прошлую версию жрайвера..

**Comment by Katrin0522** [comment]
Проверила, сброс на кнопках работает не очень, либо правый либо левый контроллер сбрасывает с погрешностью поворота на 20-45 градусов влево по x. Сбрасываю через F8, так удобнее

**Comment by r57zone** [comment]
Хорошо, спасибо за тесты, обновлю тогда для всех в ближайшее время.
