### ISSUE TITLE
Controllers take an unnatural position

### ISSUE THREAD

**Issue by Katrin0522** [TrueOpenVR/TrueOpenVR-DIY#11]
When I want to swing my sword in BeatSaber, or when I try to turn to the side (to wave to a friend), my controller turns out in an incomprehensible position, along two axes, x and y. Brings great discomfort

Когда я хочу замахнуться мечом в BeatSaber, или когда пытаюсь повернуть набок(чтобы помахать подруге), у меня контроллер выворачивается в непонятном положении, по двум осям, x и y. Приносит большие неудобства

**Comment by r57zone** [comment]
К сожалению есть такая проблема (замок Эйлера), понимаю что серьезная проблема, но пока не знаю как её решить, поскольку не работал с кватернионами.
