### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by LabrentFiero** [TrueOpenVR/TrueOpenVR-DIY#14]
Здравствуйте. Можно как нибудь добавить в прошивку поддержку аналоговых пинов для поддержки джойстиков?

**Comment by r57zone** [comment]
Привет, поддержка есть, можно изменять значение от 0 до 1 плавно, 0.1, 0.2 и так далее, если речь о триггерах, если о джойстиках, то также можно изменять, от -1 до 1, с 0 в центре. В скетче просто для упрощения показано как изменять. Насколько я помню там нужно использовать analogRead функцию и читать с аналогового пина, там кажется 1024 значение, так вот вычесть от туда 512 и разделить на 512, тогда будет от -1 до 1 значения.

**Comment by r57zone** [comment]
Также конкретно в этом проекте Arduino джойстики работают так себе, рекомендую проект HadesVR, там контроллеры доделаны лучше https://github.com/HadesVR/HadesVR

**Comment by LabrentFiero** [comment]
Спасибо. Дело в том, что я не могу сейчас использовать HadesVR, потому что я поторопился и купил mpu6050. В том проекте используется датчик с магнитометром. Я конечно их уже заказал, но пока будут ехать хотел бы что-то на вашем проекте сделать)

**Comment by LabrentFiero** [comment]
В голову мысль пришла - а что если mpu9250 на контроллеры использовать, а mpu6050 зафиксировать на шлеме вместо плеча и использовать как датчик для позиционирования в пространстве для контроллеров?

**Comment by r57zone** [comment]
Можно, если есть прошивка хорошая, с калибровкой, для mpu9250.

**Comment by LabrentFiero** [comment]
Здравствуйте, есть ещё вопрос! Поставил драйвер на Razer Hydra. Работает хорошо, но где можно переназначить кнопки и изменить их свойства именно на программном уровне? Дело в том, что хват не срабатывает в некоторых играх.
![IMG_20221129_181720~2.jpg](https://user-images.githubusercontent.com/119148438/204539940-cf99b72e-33d3-484f-aef3-cf2ed0624516.jpg) полагаю что эта область должна быть былая
![IMG_20221129_181744~2.jpg](https://user-images.githubusercontent.com/119148438/204540131-c904b98e-252f-4dfb-810b-2f29453a2b81.jpg)как здесь

**Comment by r57zone** [comment]
Вот драйвер на Razer Hydra https://github.com/r57zone/Razer-Hydra-SteamVR-driver переназначения клавиш нет, но все работает как надо, грип на двух кнопках дублируется. В TrueOpenVR драйвер для гидр неисправный, частичная начальная реализация.

**Comment by r57zone** [comment]
Не забудьте отключить контроллеры в TrueOpenVR, чтобы не было сбоев и конфликтов.

**Comment by LabrentFiero** [comment]
Спасибо за помощь!
