### ISSUE TITLE
Bluetooth поддержка

### ISSUE THREAD

**Issue by NyanAlex** [TrueOpenVR/TrueOpenVR-DIY#16]
Здравствуйте. Присутствует ли возможность добавить Bluetooth к Arduino контроллерам?

**Comment by r57zone** [comment]
Здравствуйте, в этом проекте нет, в проекте https://github.com/HadesVR/HadesVR вроде контроллеры по BlueTooth работают

**Comment by wohdek21** [comment]
> Здравствуйте. Присутствует ли возможность добавить Bluetooth к Arduino контроллерам? 

Если использовать SerialBT то получится потому что это тот же сериал но только по блютузу
