### ISSUE TITLE
MPU9250

### ISSUE THREAD

**Issue by NyanAlex** [TrueOpenVR/TrueOpenVR-DIY#17]
Здравствуйте снова! Есть ли возможность использовать для Arduino контроллеров MPU9250 вместо MPU6050?

**Comment by r57zone** [comment]
Добрый день, в теории можно, но нужна готовая прошивка и у нее изменить вывод на совместимый serial.write ... Но контроллеры в этом проекте в начальной стадии сделаны, скорее для тестов, нежели чем для использования, если нужно готовое хорошее решение, то рекомендую проект HadesVR, там контроллеры доведены до ума
https://github.com/HadesVR/HadesVR

**Comment by NyanAlex** [comment]
Спасибо за совет!
