### ISSUE TITLE
TTP223 Valve Knuckles

### ISSUE THREAD

**Issue by NyanAlex** [TrueOpenVR/TrueOpenVR-DIY#18]
Здравствуйте👋🏻.  Каким образом можно реализовать сенсорную панель как в Valve Index с помощью TTP223 и можно ли?
Знаю такая фича есть в HadesVR, но я не могу на данный момент воспользоваться им.

**Comment by r57zone** [comment]
Привет, не пробовал с ним работать, судя по всему он работает как обычная кнопка
https://роботехника18.рф/%D0%B0%D1%80%D0%B4%D1%83%D0%B8%D0%BD%D0%BE-ttp223/ 
Просто получается проверяем если кнопка нажать, то записываем значение кнопки выходную переменную кнопок HadesVR

**Comment by r57zone** [comment]
if (digitalRead(...) == LOW)
	CtrlButtons |= GRIP_BTN;
https://github.com/TrueOpenVR/TrueOpenVR-DIY/blob/master/Controllers/Arduino/Controller.ino
плюс минус так

**Comment by NyanAlex** [comment]
Спасибо! буду пробывать.

**Comment by NyanAlex** [comment]
И еще один момент

**Comment by NyanAlex** [comment]
До сих пор нет инструкции для позиционирования 2-мя MPU6050?

**Comment by r57zone** [comment]
Нет, не знаю как это реализовать, да и текущая реализация чисто начальная, тестовая, для полноценных контроллеров не годится

**Comment by NyanAlex** [comment]
спасибо за всю информацию!👍
