### ISSUE TITLE
ESP32 Instead of arduino

### ISSUE THREAD

**Issue by wohdek21** [TrueOpenVR/TrueOpenVR-DIY#19]
Hello, may i use ESP32 Wroom with WIFI and bluetooth instead of arduino

**Comment by r57zone** [comment]
Hello, there is no such support

**Comment by wohdek21** [comment]
Ok, thx

**Comment by wohdek21** [comment]
How can i add an support with SerialBT.write?

**Comment by r57zone** [comment]
Unfortunately this is not supported

**Comment by wohdek21** [comment]
Driver is using Serial right?
what if i change data get method in driver program

**Comment by wohdek21** [comment]
is it possible to use FreePIE to emulate arduino that connected with input from ESP32 connected by bluetooth
