### ISSUE TITLE
arduino head tracking not working

### ISSUE THREAD

**Issue by quirosaur** [TrueOpenVR/TrueOpenVR-DIY#2]
I have followed the guide on crating head tracker with arduino nano and mpu 6050, i calibrated and flashed the correct code in arduino. in serial monitor, lot of stuff is showing up, but when selecting arduinocontrollers as a driver, only gray screen shows up. when using keyboard driver, vr screen works.

**Comment by r57zone** [comment]
Use the Splitter driver (Keyboard HMD & Arduino controllers)

**Comment by quirosaur** [comment]
if i'm using it, the screen is still gray

EDIT: when using the head tracker, vr screen is gray, and when using splitter to utilize both keyboard and head tracker (arduinocontrollers-driver), the screen is gray

**Comment by r57zone** [comment]
Steam by default turns off the screen if there is no head movement.
To track the head, you need to use the RazorIMU driver.

**Comment by quirosaur** [comment]
razorIMU has same result, screen turns gray as soon as i start steamVR, bigscreen or vivecraft.
