### ISSUE TITLE
controller is mad

### ISSUE THREAD

**Issue by wohdek21** [TrueOpenVR/TrueOpenVR-DIY#23]
Hello, i'm made a controller with flashed controller.ino in it and he is mad, all buttons are pressing randomly without buttons input, and mpu6050 are not giving any data for pitch roll and yaw

**Comment by r57zone** [comment]
Hello, you need to purge the serial input, it seems F7 or ALT + F7, more details in the driver description in trueopenvr-drivers.

**Comment by wohdek21** [comment]
thanks i will try

**Comment by wohdek21** [comment]
it worked thanks

**Comment by wohdek21** [comment]
it's semi working

**Comment by wohdek21** [comment]
he is reading but sometimes is 0 or random number

**Comment by wohdek21** [comment]
and no buttons
