### ISSUE TITLE
Screen orientation of HMD

### ISSUE THREAD

**Issue by anon888** [TrueOpenVR/TrueOpenVR-DIY#3]
Hello, I have buyed the screen for the HMD, the screen works ok but the orientation is wrong, the screen is vertical, and I can't find a way to rotate the screen using the controller board. Does this have to be done in software (windows or nvidia control panel) or on the same controller board?.

**Comment by r57zone** [comment]
Hello, you can change the display orientation in the Windows settings.

**Comment by anon888** [comment]
Ok thanks, I was getting a little worried. I'm gonna close this issue.
