### ISSUE TITLE
Add vibration to controllers

### ISSUE THREAD

**Issue by Artemiy-Z** [TrueOpenVR/TrueOpenVR-DIY#5]
How can i add vibration?

**Comment by r57zone** [comment]
Are you talking about Arduino controllers?

**Comment by Artemiy-Z** [comment]
Yes

**Comment by r57zone** [comment]
Have you assembled your controllers entirely? Do they work well and only vibration remains?
I don't know how exactly the vibration is done, but it seems like a mosfet transistor is needed to regulate the speed of rumble motor.

**Comment by Artemiy-Z** [comment]
I haven't made controllers yet... But i want to know how get information about vibration from steamvr.

**Comment by Artemiy-Z** [comment]
I plan to make it in the future

**Comment by r57zone** [comment]
There is no vibration support for Arduino yet, because first you need someone to check to make vibration, in principle, on Arduino (motor + Mosfet), and only then add support.

**Comment by Artemiy-Z** [comment]
https://techzeero.com/arduino-tutorials/vibration-motor-with-arduino/
How i can see, vibration motor can work with Arduino

**Comment by Artemiy-Z** [comment]
https://valvesoftware.github.io/steamvr_unity_plugin/api/Valve.VR.ISteamVR_Action_Vibration.html
Can i/you use this to add vibration (if it possible on Arduino)?

**Comment by r57zone** [comment]
[Vibration support](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR/blob/master/OpenVR/samples/driver_sample/driver_sample.cpp#L792) is included in the driver in SteamVR, but it is not added to the Arduino sketch and [TrueOpenVR Adrduino driver](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/blob/master/C%2B%2B/ArduinoControllers/ArduinoControllers.cpp#L484). 
Maybe I'll add this later.

**Comment by Artemiy-Z** [comment]
Is it work?
