### ISSUE TITLE
Use analog stick?

### ISSUE THREAD

**Issue by Artemiy-Z** [TrueOpenVR/TrueOpenVR-DIY#6]
How can i modify your code to work with analog stick?

**Comment by r57zone** [comment]
https://github.com/TrueOpenVR/TrueOpenVR-DIY/blob/master/Controllers/Arduino/Controller.ino#L87-L98
We read the analog value of the stick on the Arduino, it seems it is 0 to 1023, we convert it to the range from -1 to 1.

**Comment by Artemiy-Z** [comment]
So, can it be in float type?

**Comment by r57zone** [comment]
Yep

**Comment by Artemiy-Z** [comment]
Okay, thanks
