### ISSUE TITLE
How to do positioning DIY Arduino Controller?

### ISSUE THREAD

**Issue by Katrin0522** [TrueOpenVR/TrueOpenVR-DIY#8]
ENG:
I made an Arduino controller, since you did not write a diagram for connecting a second IMU to Arduino. Option 1 is not suitable, I thought about the second option, where PS EYE is needed. I read the instructions for PsMoveService - there is no description of my binding DIY Arduino Controller. If you know, tell me how.
RU:
Я сделал контроллер на основе Arduino, так как вы не написали схему подключения второго датчика - 1 Вариант не подходит. Я думал на счёт второго варианта, где нужен PS Eye. Почитал инструкцию по PsMoveService - там не описана привязка DIY контроллера как контроллер. Если в ы знаете как это осуществить - скажите пожалуйста.

**Comment by r57zone** [comment]
https://github.com/r57zone/PSMoveService-receive-position/blob/master/README.md

**Comment by Katrin0522** [comment]
**Eng**

Thank you, only position tracking worked HMD. But when I try to use the controller, ps eye start tracking the controller like a HMD. HMD color Red, Controller is Blue... What am I doing wrong?

**Rus**

Спасибо, трекинг позиционный работает на очках. Но когда я пытаюсь использовать контроллер, камера PS захватывает позицию контрлллера вместо шлема.. Цвет шлема красный, контрлллера - Синий. Что я делаю не так?

**Comment by Katrin0522** [comment]
Or do I need to do something in TrueOpenVR to make everything work fine?

**Comment by r57zone** [comment]
You need to change the index somewhere in the psmoveservice configs 

Нужно изменить index где-то в конфигах psmoveservice

**Comment by Katrin0522** [comment]
Индекс в конфиге контроллера в конфиге psmove? На какое значение нужно изменить?

**Comment by Katrin0522** [comment]
Я потыкал конфиг, теперь вообще контроллер перестал показываться. В TrueOpenVR стоят на контроллерах PSMoveService и ArduinoControllers. Никаких признаков жизни

**Comment by r57zone** [comment]
Не помню, но там есть порядок какой-то в PSMoveService конфигах

**Comment by Katrin0522** [comment]
Это конечно прекрасненько, извиняюсь, но можете конкретнее сказать что за порядок и в каких конфигах?

**Comment by r57zone** [comment]
Я бы рад, но уже не помню, настраивал года 4 назад

**Comment by r57zone** [comment]
где-то в инструкциях в DIY должны быть англоязычные видео, где это описывается, можно включить субтитры или просто понять по видео.

**Comment by Katrin0522** [comment]
Я пересмотрела множество видео, не нашла нужного, а в инструкциях тоже ничего особого нет...qwq
А я уже в один вложила ~ 1.5к, будет грустно если всё в пустую будет:)

**Comment by r57zone** [comment]
virtual hmd на 1
https://youtu.be/IunGVk89-TY?t=182
hmd color
https://youtu.be/IunGVk89-TY?t=257

**Comment by Katrin0522** [comment]
Удивительно, но это я смотрела и делала как там, трекинг головы идеален, а вот контроллер вместе с TrueOpenVR, крашит стим

**Comment by r57zone** [comment]
Контроллер PSMove?

**Comment by Katrin0522** [comment]
Контроллер на Arduino, отдельно без сервиса PSMove в выборе на positions в TrueOpenVR в SteamVR спокойно работает, крутится как положено, кнопки работают. 
А как только выбираю сервисы в опции позиция на контроллер, то при запуске стимвр идёт крашя посредством чего все дополнения отрубаются, и при повторном включении без изменения настроек происходит тоже самое.

**Comment by r57zone** [comment]
Может сплиттер плагин неверно настроен, нужно перепроверить битность dll и прочее, кажется в видео это было

**Comment by Katrin0522** [comment]
У меня 64Бит система..  в каждом сплитере своей битности должны быть своей битности dll.. так? -3-

**Comment by r57zone** [comment]
ага, например, PSMoveService64.dll

**Comment by Katrin0522** [comment]
Интересный вопрос.. сейчас посмотрю

**Comment by Katrin0522** [comment]
В 32 и 64 бит SplitterAdvance всё нормально..

**Comment by r57zone** [comment]
Есть еще такой вариант https://www.youtube.com/watch?v=bkB__YZT6cA можно попробовать

**Comment by Katrin0522** [comment]
Посмотрела.. предлагаете изменить эти жва параметра ? могу попробовать завтра.. И вопрос.. за 4 года еще не появился способ подключения двух IMU одновременно?:)

**Comment by r57zone** [comment]
Поддержка в драйвере есть, но поддержки в Arduino нет, проектом больше не занимаюсь

**Comment by Katrin0522** [comment]
Жаль.. тогда попробую то что было в видео.. если это не удовлетворит, брошу идею создания бюджетного vr комплекта..

**Comment by Katrin0522** [comment]
Не поленилась глянуть что сейчас у меня.. так понимаю я нужно будет поиграться с этими двумя парамнтрами.. shoulder yaw и pitch.. завтра попробую

**Comment by Katrin0522** [comment]
В общем.. попробовала.. позиционирование конечно относительное.. но хоть что-то.. каким образом можно изменить длину предплечья и плеча и вообще высоту контроллера в драйвере? Ибо в vr у меня не состыкуются руки по примерному положениб, из-за чего мозг ломается и путаюсь.

**Comment by r57zone** [comment]
В конфиге, в папке TrueOpenVRSettings

**Comment by Katrin0522** [comment]
Спасибо за всю помощь... Попробовала я этот тип позиционирования, жить можно. Но тут такой прикол, что у меня исчезли краши с сервисом😅. Сейчас имею почти рабочее позиционирование(дрожит, но это не в этой теме обсуждать буду). То что запускается нормально драйвер через раз-два поняла. Но теперь образовалась новая проблемка. 1-ый контроллер собрала на оригинальном Arduino, 2-ой начала собирать этой ночью на китайской "рабочей" реплике Arduino - данные выводит с задержкой, да только не в оси вращения, а в форму Buttons и в форму что нажато. Пробовала переподключать платку, перезаливать скетч, тоже самое. Может это из-за китайской ардуинки?

**Comment by r57zone** [comment]
Вроде нет разницы китайская или нет

**Comment by Katrin0522** [comment]
По моему есть и велика в моем случае. оригинальная плата быстро работает и нормально и спокойно дает значения гироскопа куда надо, и драйвер сам подхватывает пк.
Вот драйвер на китай искала минут 20, как минимум, нашла фиг пойми где, загружает скетч на китай через раз, ну и симптомы которые я описала в прошлом коменте.. Буду покупать оригинальную ардуинку, думаю всё решится.

**Comment by Katrin0522** [comment]
Такой вопрос, Nano и  Uno отсутствуют, есть Leonardo, подойдет для контроллера (с точки зрения возможностей)

**Comment by Katrin0522** [comment]
М... Купила Leonardo.. залила скетч.. в COM порте пустота..

**Comment by Katrin0522** [comment]
Спасибо за всю ту помощь, что вы дали.
